use jtbl to show data

diff --git a/ges-tool b/ges-tool
--- a/ges-tool
+++ b/ges-tool
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.6 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.0.7 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -34,7 +34,8 @@ ges_tool_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Perform a single unstructured search query\n" "usearch"
+  printf "  %s   Install dependent tools\n" "install-dependencies"
+  printf "  %s   Perform a single unstructured search query\n" "usearch             "
   echo
 
   # :command.long_usage
@@ -66,6 +67,38 @@ ges_tool_usage() {
 }
 
 # :command.usage
+ges_tool_install_dependencies_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "ges-tool install-dependencies - Install dependent tools\n"
+    echo
+
+  else
+    printf "ges-tool install-dependencies - Install dependent tools\n"
+    echo
+
+  fi
+
+  printf "Alias: i\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  ges-tool install-dependencies\n"
+  printf "  ges-tool install-dependencies --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
 ges_tool_usearch_usage() {
   if [[ -n $long_usage ]]; then
     printf "ges-tool usearch - Perform a single unstructured search query\n"
@@ -91,8 +124,13 @@ ges_tool_usearch_usage() {
 
     # :command.usage_flags
     # :flag.usage
-    printf "  %s\n" "--force, -f"
-    printf "    Overwrite existing files\n"
+    printf "  %s\n" "--minimal, -m"
+    printf "    only show the minumum fields\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--csv, -c"
+    printf "    output to csv\n"
     echo
 
     # :command.usage_fixed_flags
@@ -176,13 +214,41 @@ inspect_args() {
 
 # :command.command_functions
 # :command.function
+ges_tool_install_dependencies_command() {
+  # src/install_dependencies_command.sh
+  if [ -f "./jtbl" ]; then
+    echo "The jbtl tool is already installed."
+  else
+    # Determine the platform.
+    platform=$(uname -s)-$(uname -m)
+    # to upper case
+    platform_lower=${platform,,}
+
+    # Download the CLI tool for the current platform.
+    wget "https://github.com/kellyjonbrazil/jtbl/releases/download/v1.5.2/jtbl-1.5.2-${platform_lower}.tar.gz"
+
+    tar -xvf jtbl-1.5.2-${platform_lower}.tar.gz
+    echo "The jbtl tool installed."
+  fi
+}
+
+# :command.function
 ges_tool_usearch_command() {
   # src/usearch_command.sh
   querystring=${args[query]}
   page_size=${args[page_size]}
-  #echo ${query}
-  curl -X POST -H "Authorization: Bearer $(gcloud auth print-access-token)" -H "Content-Type: application/json" "https://discoveryengine.googleapis.com/v1alpha/projects/${GCP_PROJECT_NUMBER}/locations/global/collections/default_collection/dataStores/${DATASTORE_NAME}/servingConfigs/default_search:search" -d '{ "query": "'"${querystring}"'", "page_size": "5", "offset": 0 , "contentSearchSpec": { "snippetSpec":{"maxSnippetCount": 2,"referenceOnly": false}, "extractiveContentSpec": {"maxExtractiveSegmentCount": 1} } }' \
-  | jq -r '[.results[0].document.derivedStructData.link, .results[0].document.derivedStructData.snippets[0].snippet | @csv'
+  minimal=${args[--minimal]}
+  csv=${args[--csv]}
+  if [[ $minimal ]]; then
+      curl -s  -X POST -H "Authorization: Bearer $(gcloud auth print-access-token)" -H "Content-Type: application/json" "https://discoveryengine.googleapis.com/v1alpha/projects/${GCP_PROJECT_NUMBER}/locations/global/collections/default_collection/dataStores/${DATASTORE_NAME}/servingConfigs/default_search:search" -d '{ "query": "'"${querystring}"'", "page_size": "5", "offset": 0 , "contentSearchSpec": { "snippetSpec":{"maxSnippetCount": 3}, "summarySpec":{"summaryResultCount": 5} } }' \
+      | jq  '[{summary: .summary.summaryText, link: .results[0].document.derivedStructData.link}]' | jtbl
+  elif  [[ $csv ]]; then
+      curl -s -X POST -H "Authorization: Bearer $(gcloud auth print-access-token)" -H "Content-Type: application/json" "https://discoveryengine.googleapis.com/v1alpha/projects/${GCP_PROJECT_NUMBER}/locations/global/collections/default_collection/dataStores/${DATASTORE_NAME}/servingConfigs/default_search:search" -d '{ "query": "'"${querystring}"'", "page_size": "5", "offset": 0 , "contentSearchSpec": { "snippetSpec":{"maxSnippetCount": 3}, "summarySpec":{"summaryResultCount": 5}} }' \
+      | jq  '[{summary: .summary.summaryText, link: .results[0].document.derivedStructData.link}]' | jtbl -c
+  else
+      curl -X POST -H "Authorization: Bearer $(gcloud auth print-access-token)" -H "Content-Type: application/json" "https://discoveryengine.googleapis.com/v1alpha/projects/${GCP_PROJECT_NUMBER}/locations/global/collections/default_collection/dataStores/${DATASTORE_NAME}/servingConfigs/default_search:search" -d '{ "query": "'"${querystring}"'", "page_size": "5", "offset": 0 , "contentSearchSpec": { "snippetSpec":{"maxSnippetCount": 3}, "summarySpec":{"summaryResultCount": 5} } }'
+
+  fi
 }
 
 # :command.parse_requirements
@@ -225,6 +291,13 @@ parse_requirements() {
   case $action in
     -*) ;;
 
+    install-dependencies | i)
+      action="install-dependencies"
+      shift
+      ges_tool_install_dependencies_parse_requirements "$@"
+      shift $#
+      ;;
+
     usearch | s)
       action="usearch"
       shift
@@ -244,6 +317,50 @@ parse_requirements() {
       ;;
 
   esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+ges_tool_install_dependencies_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        ges_tool_install_dependencies_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="install-dependencies"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -294,10 +411,18 @@ ges_tool_usearch_parse_requirements() {
     key="$1"
     case "$key" in
       # :flag.case
-      --force | -f)
+      --minimal | -m)
 
         # :flag.case_no_arg
-        args['--force']=1
+        args['--minimal']=1
+        shift
+        ;;
+
+      # :flag.case
+      --csv | -c)
+
+        # :flag.case_no_arg
+        args['--csv']=1
         shift
         ;;
 
@@ -356,6 +481,7 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "install-dependencies") ges_tool_install_dependencies_command ;;
     "usearch") ges_tool_usearch_command ;;
   esac
 }
