added tests for init

diff --git a/ges-tool b/ges-tool
--- a/ges-tool
+++ b/ges-tool
@@ -276,13 +276,28 @@ ges_tool_init_command() {
     # to upper case
     platform_lower=${platform,,}
 
-    # Download the CLI tool for the current platform.
-    curl -LO https://github.com/kellyjonbrazil/jtbl/releases/download/v1.5.2/jtbl-1.5.2-"${platform_lower}".tar.gz
+     # Destination file to save the downloaded content
+    file_path=jtbl-1.5.2-"${platform_lower}".tar.gz
 
-    tar -xvf jtbl-1.5.2-"${platform_lower}".tar.gz
+    url=https://github.com/kellyjonbrazil/jtbl/releases/donload/v1.5.2/jtbl-1.5.2-"${platform_lower}".tar.gz
 
-    rm jtbl-1.5.2-"${platform_lower}".tar.gz
-    echo "The jbtl tool installed."
+    # Use curl to download the file
+    response_code=$(curl -LO "$url" -w "%{http_code}")
+
+    # Check the HTTP status code
+    if [ "$response_code" -eq 200 ]; then
+      echo "File $file_path downloaded successfully (HTTP status code: $response_code)."
+      echo "The jbtl tool installed."
+      # You can further process the downloaded file or display a success message.
+    else
+      echo "File download failed (HTTP status code: $response_code)."
+      echo "The jbtl tool NOT installed. Check you have an internet connection."
+      exit 1
+      # Handle the error or display an error message.
+    fi
+    tar -xzf "$file_path"
+
+    rm "$file_path"
   fi
   echo "Checking for gcloud authetication"
   token=$(gcloud auth print-access-token)
