Added mAR, mrr, ndcg

diff --git a/vlvt b/vlvt
--- a/vlvt
+++ b/vlvt
@@ -56,12 +56,12 @@ vlvt_usage() {
     printf "%s\n" "$(bold "Environment Variables:")"
 
     # :environment_variable.usage
-    printf "  %s\n" "$(cyan "GCP_PROJECT_NUMBER (required)")"
-    printf "    Set your GCP Vertex AI Search Project Number (not project id)\n"
+    printf "  %s\n" "$(cyan "VAI_SEARCH_PROJECT_NUMBER (required)")"
+    printf "    Set your GCP Vertex AI Search Project Number (NOT project ID)\n"
     echo
 
     # :environment_variable.usage
-    printf "  %s\n" "$(cyan "DATASTORE_NAME (required)")"
+    printf "  %s\n" "$(cyan "VAI_SEARCH_DATASTORE_NAME (required)")"
     printf "    Vertex AI Search Data Store name of the format <data_store>_<some_number>\"\n"
     echo
 
@@ -138,7 +138,7 @@ vlvt_search_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--format, -f FORMAT")"
     printf "    format of output. CSV is default if no option is specified\n"
-    printf "    Allowed: csv, table, jsonl\n"
+    printf "    Allowed: csv, table, jsonl, raw\n"
     printf "    Default: csv\n"
     echo
 
@@ -255,12 +255,12 @@ vlvt_verify_usage() {
     printf "%s\n" "$(bold "Environment Variables:")"
 
     # :environment_variable.usage
-    printf "  %s\n" "$(cyan "PROJECT_ID (required)")"
+    printf "  %s\n" "$(cyan "TEXT_BISON_PROJECT_ID (required)")"
     printf "    GCP Project where Palm text-bison API is enabled and available\n"
     echo
 
     # :environment_variable.usage
-    printf "  %s\n" "$(cyan "LOCATION_ID (required)")"
+    printf "  %s\n" "$(cyan "TEXT_BISON_LOCATION_ID (required)")"
     printf "    GCP Region to use for the text-bison API is enabled and available\n"
     echo
 
@@ -320,6 +320,111 @@ inspect_args() {
 }
 
 # :command.user_lib
+# src/lib/calc_mrr_at_2.sh
+# shellcheck disable=SC2148
+function rank_reciprocal_at_2() {
+  local actual_link_1="$1"
+  local actual_link_2="$2"
+  local expected_link_1="$3"
+  local expected_link_2="$4"
+
+  local rank=0
+
+  # For each document link in the expected results, check if it is also in the actual results.
+  if [ "$actual_link_1" == "${expected_link_1}" ]; then
+        rank=$(echo "scale=4; 1" | bc)
+  elif [ "$actual_link_2" == "${expected_link_1}" ]; then
+        rank=$(echo "scale=4; 1/2" | bc)
+  elif [ "$actual_link_1" == "${expected_link_2}" ]; then
+        rank=$(echo "scale=4; 1/2" | bc)
+  elif [ "$actual_link_2" == "${expected_link_2}" ]; then
+        rank=$(echo "scale=4; 1/2" | bc)
+  fi
+
+  # Return the rank_reciprocal_at_2 value.
+  echo "$rank"
+}
+
+# src/lib/calc_ndcg.sh
+function calc_ndcg() {
+
+    local link_1
+    local link_2
+    local expected_link_1
+    local expected_link_2
+    local relevance_scores
+    local ideal_relevance_scores
+    local dcg
+    local idcg
+    local ndcg
+
+    link_1="$1"
+    link_2="$2"
+    expected_link_1="$3"
+    expected_link_2="$4"
+
+    # Define relevance and ideal relevance scores
+    relevance_scores=()
+    if [[ "$link_1" == "$expected_link_1" ]]; then
+        relevance_scores+=(2)
+    elif [[ "$link_1" == "$expected_link_2" ]]; then
+        relevance_scores+=(1)
+    else
+        relevance_scores+=(0)
+    fi
+
+    if [[ "$link_2" == "$expected_link_1" ]]; then
+        relevance_scores+=(1)
+    elif [[ "$link_2" == "$expected_link_2" ]]; then
+        relevance_scores+=(1)
+    else
+        relevance_scores+=(0)
+    fi
+
+    # Calculate and print NDCG for current row
+    dcg=0
+    for i in "${!relevance_scores[@]}"; do
+        local relevance_score="${relevance_scores[$i]}"
+        dcg=$(echo "scale=10; $dcg + $relevance_score / l($i + 2)" | bc -l)
+    done
+    #echo "dcg=$dcg"
+
+    ideal_relevance_scores=()
+    ideal_relevance_scores+=(2)
+    ideal_relevance_scores+=(2)
+
+    idcg=0
+    for i in "${!ideal_relevance_scores[@]}"; do
+        local ideal_relevance_score="${ideal_relevance_scores[$i]}"
+        idcg=$(echo "scale=10; $idcg + $ideal_relevance_score / l($i + 2)" | bc -l)
+    done
+    #echo "idcg=$idcg"
+
+    ndcg=0
+    if (( $(echo "$idcg > 0" | bc -l) )); then
+        ndcg=$(echo "scale=4; $dcg / $idcg" | bc -l)
+    fi
+
+    echo "$ndcg"
+}
+
+# src/lib/calc_precision_at_k.sh
+function precision_at() {
+  local actual_link="$1"
+  local expected_link_1="$2"
+  local expected_link_2="$3"
+  local position="$4"
+  local precision=0
+  # For each document link in the expected results, check if it is also in the actual results.
+  if [ "$actual_link" == "${expected_link_1}" ]; then
+        precision=$(echo "scale=4; $position/1" | bc)
+  elif [ "$actual_link" == "${expected_link_2}" ]; then
+        precision=$(echo "scale=4; $position/2" | bc)
+  fi
+  # Return the p value.
+  echo "$precision"
+}
+
 # src/lib/call_palm_text_bison.sh
 # shellcheck disable=SC2148
 call_palm_text_bison() {
@@ -329,7 +434,7 @@ call_palm_text_bison() {
     examples - answer_1: I was created by X. answer_2: X created me. output:same
 
     answer_1:There are 52 days in a year. answer_2: A year is fairly long. output:different"
-    full_payload=$prompt" Now answer answer_1: $summary,
+    full_payload=$prompt". Now answer answer_1: $summary,
         answer_2: $expected_summary
         output:"
 
@@ -349,7 +454,7 @@ call_palm_text_bison() {
     }"
     #echo "$jsonPayload"
 
-    API_ENDPOINT="${LOCATION_ID}-aiplatform.googleapis.com"
+    API_ENDPOINT="${TEXT_BISON_LOCATION_ID}-aiplatform.googleapis.com"
     MODEL_ID="text-bison"
 
     match_result=$(curl \
@@ -357,7 +462,7 @@ call_palm_text_bison() {
     -X POST \
     -H "Authorization: Bearer $token" \
     -H "Content-Type: application/json" \
-    "https://${API_ENDPOINT}/v1/projects/${PROJECT_ID}/locations/${LOCATION_ID}/publishers/google/models/${MODEL_ID}:predict" -d "$jsonPayload")
+    "https://${API_ENDPOINT}/v1/projects/${TEXT_BISON_PROJECT_ID}/locations/${TEXT_BISON_LOCATION_ID}/publishers/google/models/${MODEL_ID}:predict" -d "$jsonPayload")
     error=$(echo "$match_result" | jq '.error.code' )
     if [ -z "$error" ]; then
         error_message=$(echo "$match_result" | jq '.error.message' )
@@ -372,7 +477,7 @@ call_palm_text_bison() {
 # shellcheck disable=SC2148
 call_vertex_ai_search() {
 
-    command_output=$(curl -s -X POST -H "Authorization: Bearer $token" -H "Content-Type: application/json" "https://discoveryengine.googleapis.com/v1alpha/projects/${GCP_PROJECT_NUMBER}/locations/global/collections/default_collection/dataStores/${DATASTORE_NAME}/servingConfigs/default_search:search" -d '{ "query": "'"${query}"'", "page_size": "5", "offset": 0 , "contentSearchSpec": { "snippetSpec":{"maxSnippetCount": 2}, "summarySpec":{"summaryResultCount": 3}} }')
+    command_output=$(curl -s -X POST -H "Authorization: Bearer $token" -H "Content-Type: application/json" "https://discoveryengine.googleapis.com/v1alpha/projects/${VAI_SEARCH_PROJECT_NUMBER}/locations/global/collections/default_collection/dataStores/${VAI_SEARCH_DATASTORE_NAME}/servingConfigs/default_search:search" -d '{ "query": "'"${query}"'", "page_size": "5", "offset": 0 , "contentSearchSpec": { "snippetSpec":{"maxSnippetCount": 2}, "summarySpec":{"summaryResultCount": 3}} }')
 
     error=$(echo "$command_output" | jq '.error.code' )
     if [ -z "$error" ]; then
@@ -430,6 +535,9 @@ format_output() {
         echo "$output" | ./jtbl -c
     elif [ "$format" == "jsonl" ]; then
         echo "$output"
+
+    elif [ "$format" == "raw" ]; then
+        echo "$command_output"
 
     fi
 
@@ -530,7 +638,7 @@ vlvt_bsearch_command() {
           query=$line
           call_vertex_ai_search
 
-          output+="{\"summary\": \"$summary\", \"link_1\": \"$link_1\", \"link_2\": \"$link_2\", \"link_3\": \"$link_3\"}"$'\n'
+          output+="{\"question\": \"$query\", \"summary\": \"$summary\", \"link_1\": \"$link_1\", \"link_2\": \"$link_2\", \"link_3\": \"$link_3\"}"$'\n'
 
       fi
   done < "$input_file"
@@ -593,12 +701,9 @@ vlvt_verify_command() {
 
   output=""
   summary_correct_count=0
-  link_1_correct_count=0
-  link_2_correct_count=0
   total_documents=${#ids[@]}
   # Loop through the entries and call vertex ai search and then call palm bison to match the summaries
   for ((i = 0; i < total_documents; i++)); do
-    #echo "ID: ${ids[$i]}, query: ${queries[$i]}, expected_summary: ${expected_summaries[$i]}, expected_document_link: ${expected_document_links[$i]}"
     # Skip line with empty id field
     if [ -z "${ids[$i]}" ]; then
         continue;
@@ -612,40 +717,35 @@ vlvt_verify_command() {
       query=${queries[$i]}
       call_vertex_ai_search
 
+      # Calculate precision p@0 this tells us if the first result is perfect match
       if [ "$link_1" == "${expected_link_1}" ]; then
-          link_1_match="matched"
           p0_precision=1.0
       else
 
-          link_1_match="not_matched"
           p0_precision=0.0
       fi
 
-      if [[ "$link_1" == "${expected_link_1}" || "$link_1" == "${expected_link_2}" ]]; then
-          link_1_correct_count=$((link_1_correct_count + 1))
-      fi
+      # Calculate precision
+      # p@1
+      precision_1=$(precision_at  "$link_1" "${expected_link_1}" "${expected_link_2}" 1 )
+       # p@2
+      precision_2=$(precision_at  "$link_2" "${expected_link_1}" "${expected_link_2}" 2 )
 
-      p1_precision=$(echo "scale=4; $link_1_correct_count / ($i+1) " | bc)
 
-      if [ "$link_2" == "${expected_link_2}" ]; then
-          link_2_match="matched"
-      else
+      map=$(echo "scale=4; ($precision_1 + $precision_2) / 2 " | bc)
 
-          link_2_match="not_matched"
-      fi
+      mrr=$(rank_reciprocal_at_2 "${link_1}" "${link_2}" "${expected_link_1}" "${expected_link_2}")
 
-      if [[ "$link_2" == "${expected_link_1}" || "$link_2" == "${expected_link_2}" ]]; then
-          link_2_correct_count=$((link_2_correct_count + 1))
-      fi
-
-      p2_precision=$(echo "scale=4; $link_2_correct_count / ($i+1) " | bc)
+      # NDCG
+      ndcg=$(calc_ndcg "${link_1}" "${link_2}" "${expected_link_1}" "${expected_link_2}")
+      #echo "$ndcg"
+      # Calculate the
 
       expected_summary=${expected_summaries[$i]}
-      # Verify the summary by calling text-bison
+      # Verify the summary by calling text-bison to do a semantic comparison to see if it matches expected summary
       call_palm_text_bison
 
       # Calculate precision
-
       if [ "$summary_match" == "same" ];then
 
         summary_correct_count=$((summary_correct_count + 1))
@@ -655,7 +755,7 @@ vlvt_verify_command() {
 
       # Create JSONL output
       #output+="{\"id\": \"$current_id\", \"actual_summary\": \"$summary\", \"expected_summary\": \"$expected_summary\", \"summary_match\": \"$summary_match\" , \"expected_link_1\": \"$expected_link_1\"  ,  \"actual_link_1\": \"$link_1\", \"link_1_match\": \"$link_1_match\", \"expected_link_2\": \"$expected_link_2\" ,  \"actual_link_2\": \"$link_2\"  ,\"link_2_match\": \"$link_2_match\", \"summary_p\": \"$summary_precision\" ,  \"@p0\": \"$p0_precision\", \"@p1\": \"$p1_precision\", \"@p2\": \"$p2_precision\"}"$'\n'
-      output+="{\"id\": \"$current_id\", \"actual_summary\": \"$summary\", \"expected_summary\": \"$expected_summary\" , \"expected_link_1\": \"$expected_link_1\"  ,  \"actual_link_1\": \"$link_1\", \"expected_link_2\": \"$expected_link_2\" ,  \"actual_link_2\": \"$link_2\" , \"summary_p\": \"$summary_precision\" ,  \"@p0\": \"$p0_precision\", \"@p1\": \"$p1_precision\", \"@p2\": \"$p2_precision\"}"$'\n'
+      output+="{\"id\": \"$current_id\", \"question\": \"$query\", \"actual_summary\": \"$summary\", \"expected_summary\": \"$expected_summary\" , \"expected_link_1\": \"$expected_link_1\"  ,  \"actual_link_1\": \"$link_1\", \"expected_link_2\": \"$expected_link_2\" ,  \"actual_link_2\": \"$link_2\" , \"summary_p\": \"$summary_precision\" ,  \"@p0\": \"$p0_precision\", \"mrr@2\": \"$mrr\",  \"mAP@2\": \"$map\", \"ndcg@2\": \"$ndcg\"}"$'\n'
 
     fi
   done
@@ -689,12 +789,12 @@ parse_requirements() {
 
   # :command.environment_variables_filter
 
-  if [[ -z "${GCP_PROJECT_NUMBER:-}" ]]; then
-    printf "missing required environment variable: GCP_PROJECT_NUMBER\n" >&2
+  if [[ -z "${VAI_SEARCH_PROJECT_NUMBER:-}" ]]; then
+    printf "missing required environment variable: VAI_SEARCH_PROJECT_NUMBER\n" >&2
     exit 1
   fi
-  if [[ -z "${DATASTORE_NAME:-}" ]]; then
-    printf "missing required environment variable: DATASTORE_NAME\n" >&2
+  if [[ -z "${VAI_SEARCH_DATASTORE_NAME:-}" ]]; then
+    printf "missing required environment variable: VAI_SEARCH_DATASTORE_NAME\n" >&2
     exit 1
   fi
 
@@ -845,6 +945,21 @@ vlvt_search_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+  if command -v curl >/dev/null 2>&1; then
+    deps['curl']="$(command -v curl | head -n1)"
+  else
+    printf "missing dependency: curl\n" >&2
+    exit 1
+  fi
+
+  if command -v jq >/dev/null 2>&1; then
+    deps['jq']="$(command -v jq | head -n1)"
+  else
+    printf "missing dependency: jq\n" >&2
+    exit 1
+  fi
+
   # :command.command_filter
   action="search"
 
@@ -899,8 +1014,8 @@ vlvt_search_parse_requirements() {
   [[ -n ${args['--format']:-} ]] || args['--format']="csv"
 
   # :command.whitelist_filter
-  if [[ ${args['--format']:-} ]] && [[ ! ${args['--format']:-} =~ ^(csv|table|jsonl)$ ]]; then
-    printf "%s\n" "--format must be one of: csv, table, jsonl" >&2
+  if [[ ${args['--format']:-} ]] && [[ ! ${args['--format']:-} =~ ^(csv|table|jsonl|raw)$ ]]; then
+    printf "%s\n" "--format must be one of: csv, table, jsonl, raw" >&2
     exit 1
   fi
 
@@ -923,6 +1038,21 @@ vlvt_bsearch_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
+  if command -v curl >/dev/null 2>&1; then
+    deps['curl']="$(command -v curl | head -n1)"
+  else
+    printf "missing dependency: curl\n" >&2
+    exit 1
+  fi
+
+  if command -v jq >/dev/null 2>&1; then
+    deps['jq']="$(command -v jq | head -n1)"
+  else
+    printf "missing dependency: jq\n" >&2
+    exit 1
+  fi
 
   # :command.command_filter
   action="bsearch"
@@ -1005,12 +1135,34 @@ vlvt_verify_parse_requirements() {
 
   # :command.environment_variables_filter
 
-  if [[ -z "${PROJECT_ID:-}" ]]; then
-    printf "missing required environment variable: PROJECT_ID\n" >&2
+  if [[ -z "${TEXT_BISON_PROJECT_ID:-}" ]]; then
+    printf "missing required environment variable: TEXT_BISON_PROJECT_ID\n" >&2
     exit 1
   fi
-  if [[ -z "${LOCATION_ID:-}" ]]; then
-    printf "missing required environment variable: LOCATION_ID\n" >&2
+  if [[ -z "${TEXT_BISON_LOCATION_ID:-}" ]]; then
+    printf "missing required environment variable: TEXT_BISON_LOCATION_ID\n" >&2
+    exit 1
+  fi
+
+  # :command.dependencies_filter
+  if command -v curl >/dev/null 2>&1; then
+    deps['curl']="$(command -v curl | head -n1)"
+  else
+    printf "missing dependency: curl\n" >&2
+    exit 1
+  fi
+
+  if command -v jq >/dev/null 2>&1; then
+    deps['jq']="$(command -v jq | head -n1)"
+  else
+    printf "missing dependency: jq\n" >&2
+    exit 1
+  fi
+
+  if command -v bc >/dev/null 2>&1; then
+    deps['bc']="$(command -v bc | head -n1)"
+  else
+    printf "missing dependency: bc\n" >&2
     exit 1
   fi
 
