Added threshold flags. renamed test files.

diff --git a/vlvt b/vlvt
--- a/vlvt
+++ b/vlvt
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.3 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.4 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -238,6 +238,16 @@ vlvt_verify_usage() {
     printf "    Default: csv\n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--mrr-threshold, -t MRR-THRESHOLD")"
+    printf "    Mean Reciprocal Rank (MRR) threshold to be above. If specified it will fail\n    if MRR is below this threshold.\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--summary-threshold, -s SUMMARY-THRESHOLD")"
+    printf "    Average Summary Precision threshold to be above. If specified it will fail\n    if Average Summary Precision is below this threshold.\n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
@@ -248,7 +258,7 @@ vlvt_verify_usage() {
 
     # :argument.usage
     printf "  %s\n" "$(blue "INPUT_FILE")"
-    printf "    csv file containing queries and expected results format is -\n"
+    printf "    csv file containing queries and expected results format is - id, query,\n    expected_summary, expected_document_link_1, expected_document_link_2\n"
     echo
 
     # :command.usage_environment_variables
@@ -346,6 +356,7 @@ function rank_reciprocal_at_2() {
 }
 
 # src/lib/calc_ndcg.sh
+# shellcheck disable=SC2148
 function calc_ndcg() {
 
     local link_1
@@ -409,6 +420,8 @@ function calc_ndcg() {
 }
 
 # src/lib/calc_precision_at_k.sh
+# shellcheck disable=SC2148
+
 function precision_at() {
   local actual_link="$1"
   local expected_link_1="$2"
@@ -650,9 +663,12 @@ vlvt_bsearch_command() {
 # :command.function
 vlvt_verify_command() {
   # src/verify_command.sh
-  #inspect_args
+  # shellcheck disable=SC2148
+  # shellcheck disable=SC2154
   input_file=${args[input_file]}
   format=${args[--format]}
+  mrr_threshold=${args[--mrr-threshold]}
+  summary_threshold=${args[--summary-threshold]}
   token=${GCP_ACCESS_TOKEN}
 
   if [ -z "$token" ]; then
@@ -673,7 +689,7 @@ vlvt_verify_command() {
   # Verify column names or take any actions based on them
   expected_columns=("id" "query" "expected_summary" "expected_document_link_1" "expected_document_link_2") # Define expected column names
   if [ "${#column_names[@]}" -ne "${#expected_columns[@]}" ]; then
-    echo "Column count doesn't match!"
+    echo "Column count doesn't match! Run verify --help for format"
     exit 1
   fi
 
@@ -701,9 +717,10 @@ vlvt_verify_command() {
 
   output=""
   summary_correct_count=0
-  total_documents=${#ids[@]}
+  total_mrr=0
+  total_rows=${#ids[@]}
   # Loop through the entries and call vertex ai search and then call palm bison to match the summaries
-  for ((i = 0; i < total_documents; i++)); do
+  for ((i = 0; i < total_rows; i++)); do
     # Skip line with empty id field
     if [ -z "${ids[$i]}" ]; then
         continue;
@@ -735,10 +752,11 @@ vlvt_verify_command() {
       map=$(echo "scale=4; ($precision_1 + $precision_2) / 2 " | bc)
 
       mrr=$(rank_reciprocal_at_2 "${link_1}" "${link_2}" "${expected_link_1}" "${expected_link_2}")
+      total_mrr=$(echo "scale=4; $mrr + $total_mrr " | bc)
 
       # NDCG
       ndcg=$(calc_ndcg "${link_1}" "${link_2}" "${expected_link_1}" "${expected_link_2}")
-      #echo "$ndcg"
+
       # Calculate the
 
       expected_summary=${expected_summaries[$i]}
@@ -755,12 +773,56 @@ vlvt_verify_command() {
 
       # Create JSONL output
       #output+="{\"id\": \"$current_id\", \"actual_summary\": \"$summary\", \"expected_summary\": \"$expected_summary\", \"summary_match\": \"$summary_match\" , \"expected_link_1\": \"$expected_link_1\"  ,  \"actual_link_1\": \"$link_1\", \"link_1_match\": \"$link_1_match\", \"expected_link_2\": \"$expected_link_2\" ,  \"actual_link_2\": \"$link_2\"  ,\"link_2_match\": \"$link_2_match\", \"summary_p\": \"$summary_precision\" ,  \"@p0\": \"$p0_precision\", \"@p1\": \"$p1_precision\", \"@p2\": \"$p2_precision\"}"$'\n'
-      output+="{\"id\": \"$current_id\", \"question\": \"$query\", \"actual_summary\": \"$summary\", \"expected_summary\": \"$expected_summary\" , \"expected_link_1\": \"$expected_link_1\"  ,  \"actual_link_1\": \"$link_1\", \"expected_link_2\": \"$expected_link_2\" ,  \"actual_link_2\": \"$link_2\" , \"summary_p\": \"$summary_precision\" ,  \"@p0\": \"$p0_precision\", \"mrr@2\": \"$mrr\",  \"mAP@2\": \"$map\", \"ndcg@2\": \"$ndcg\"}"$'\n'
+      output+="{\"id\": \"$current_id\", \"summary_p\": \"$summary_precision\" ,  \"@p0\": \"$p0_precision\", \"mrr\": \"$mrr\",  \"mAP@2\": \"$map\", \"ndcg@2\": \"$ndcg\", \"question\": \"$query\", \"actual_summary\": \"$summary\", \"expected_summary\": \"$expected_summary\" , \"expected_link_1\": \"$expected_link_1\"  ,  \"actual_link_1\": \"$link_1\", \"expected_link_2\": \"$expected_link_2\" ,  \"actual_link_2\": \"$link_2\" }"$'\n'
 
     fi
   done
 
+  average_summary_precision=$(echo "scale=4; $summary_correct_count / $total_rows " | bc)
+  overall_mrr=$(echo "scale=4; $total_mrr / $total_rows " | bc)
+  mrr_string=""
+  average_summary_precision_string=""
+  exit_code=0
+  # Check if the MRR threshold is set
+  if [ -z "$mrr_threshold" ]; then
+
+    exit_code=0
+  else
+
+    if (( $(echo "$overall_mrr > $mrr_threshold" | bc -l) )); then
+       mrr_string="PASSED: MRR"
+    else
+       mrr_string="FAILED: MRR"
+       exit_code=1
+
+    fi
+
+  fi
+  if [ -z "$summary_threshold" ]; then
+
+    exit_code=$exit_code
+  else
+
+    if (( $(echo "$average_summary_precision > $summary_threshold" | bc -l) )); then
+       average_summary_precision_string="PASSED: SummaryP"
+    else
+       average_summary_precision_string="FAILED: SummaryP"
+       exit_code=1
+
+    fi
+
+  fi
+  # Summary Row
+  output+="{\"id\": \"\", \"summary_p\": \"$average_summary_precision\", \"@p0\": \"\", \"mrr\": \"$overall_mrr\",  \"mAP@2\": \"\", \"ndcg@2\": \"\", \"question\": \"\", \"actual_summary\": \"\", \"expected_summary\": \"\" , \"expected_link_1\": \"\"  ,  \"actual_link_1\": \"\", \"expected_link_2\": \"\" ,  \"actual_link_2\": \"\" }"$'\n'
+
+  if [[ -n "$mrr_threshold" || -n  "$summary_threshold" ]]; then
+    output+="{\"id\": \"\", \"summary_p\": \"$average_summary_precision_string\", \"@p0\": \"\", \"mrr\": \"$mrr_string\",  \"mAP@2\": \"\", \"ndcg@2\": \"\", \"question\": \"\", \"actual_summary\": \"\", \"expected_summary\": \"\" , \"expected_link_1\": \"\"  ,  \"actual_link_1\": \"\", \"expected_link_2\": \"\" ,  \"actual_link_2\": \"\" }"$'\n'
+  fi
+  # Summary Row
+
   format_output
+
+  exit $exit_code
 
 }
 
@@ -1184,6 +1246,36 @@ vlvt_verify_parse_requirements() {
           shift
         else
           printf "%s\n" "--format requires an argument: --format, -f FORMAT" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --mrr-threshold | -t)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--mrr-threshold']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--mrr-threshold requires an argument: --mrr-threshold, -t MRR-THRESHOLD" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --summary-threshold | -s)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--summary-threshold']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--summary-threshold requires an argument: --summary-threshold, -s SUMMARY-THRESHOLD" >&2
           exit 1
         fi
         ;;
